# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/anyexinglu"
  weibo: "http://weibo.com/u/1790889042"
  zhihu: "https://www.zhihu.com/people/an-ye-xing-lu-28"
  facebook: "https://www.facebook.com/xiayan.yang"
  #douban: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

# Site
subtitle: Keep moving

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /img/avatar.jpg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
# friends: false
#开启——
friends:
  FEX技术周刊: http://fex.baidu.com/weekly/
  十年踪迹的博客: http://blog.h5jun.com/
  奇舞周刊: http://old.75team.com/weekly/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 就职于百度INF的前端工程师一枚，喜欢研究前端开发、云计算 & 理财等领域。动漫 & 各种剧爱好者
